### ISSUE TITLE
Setting up the initial database model for messaging system

### ISSUE THREAD

**Issue by Franello16** [ahsia3/SecureSay#9]
This task involves getting started on the database for the application including:

**1.) Database structure i.e. sender, receiver, time message sent, date, etc.**

[http://www.vertabelo.com/blog/technical-articles/database-model-for-a-messaging-system](url)

**Comment by Kyle-Hodge** [comment]
This is sample code for setting up a database using Python SQL.  The first part is setting up the SQL

$ sudo apt-get install sqlite 

The following is to verify that it is correctly installed
#!/usr/bin/python
# -*- coding: utf-8 -*-
 
import sqlite3 as lite
import sys
 
con = None
 
try:
    con = lite.connect('test.db')
    cur = con.cursor()    
    cur.execute('SELECT SQLITE_VERSION()')
    data = cur.fetchone()
    print "SQLite version: %s" % data                
except lite.Error, e:   
    print "Error %s:" % e.args[0]
    sys.exit(1)
finally:    
    if con:
        con.close()
Then execute it with this

$ python test1.py

If it is correctly installed this should be the output 

SQLite version: 3.8.2

This is sto0ring dat in a database named usr.db note that the names in are just sample names

#!/usr/bin/python
# -*- coding: utf-8 -*-
 
import sqlite3 as lite
import sys
 
con = lite.connect('user.db')
 
with con:
 
    cur = con.cursor()    
    cur.execute("CREATE TABLE Users(Id INT, Name TEXT)")
    cur.execute("INSERT INTO Users VALUES(1,'Michelle')")
    cur.execute("INSERT INTO Users VALUES(2,'Sonya')")
    cur.execute("INSERT INTO Users VALUES(3,'Greg')")

Create tables with
cur.execute("CREATE TABLE Users(Id INT, Name TEXT)")

Adding to thetables is done as followed
    cur.execute("INSERT INTO Users VALUES(2,'Sonya')")
    cur.execute("INSERT INTO Users VALUES(3,'Greg')")
